# Generated by Django 5.1.4 on 2024-12-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_reservation_deleted_reservation_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="start_date",
        ),
    ]
