# Generated by Django 5.1.4 on 2025-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_alter_reservation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
