# Generated by Django 5.1.4 on 2025-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0008_reservation_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="client_name",
            field=models.CharField(max_length=100, verbose_name="Nom Client"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="commercial_advisor",
            field=models.CharField(max_length=100, verbose_name="Nom Commercial"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="criticality",
            field=models.CharField(
                choices=[("low", "Faible"), ("medium", "Moyen"), ("high", "Critique")],
                max_length=20,
                verbose_name="Criticité",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(verbose_name="Date de réservation"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_duration",
            field=models.PositiveIntegerField(
                help_text="en jours", verbose_name="Durée de la réservation"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="service_advisor",
            field=models.CharField(
                max_length=100, verbose_name="Nom conseiller de service"
            ),
        ),
    ]
